const assert = require('node:assert/strict');
const { startSandbox } = require('./test-sandbox');
async function run() {
  const sandbox = await startSandbox();
  let assertions = 0;
  const check = (condition, label) => { assert.ok(condition, label); assertions++; console.log(`PASS ${label}`); };
  async function request(path, method = 'GET', body, token, cookie) {
    const response = await fetch(sandbox.base + path, { method, headers: { 'content-type':'application/json', ...(token ? { authorization:`Bearer ${token}` }: {}), ...(cookie ? {cookie} : {}) }, ...(body ? {body:JSON.stringify(body)} : {}) });
    return { status:response.status, body:await response.json(), cookie:response.headers.get('set-cookie')?.split(';')[0] };
  }
  try {
    const login = await request('/auth/login','POST',{email:'admin@example.test',password:'TestOnly!12345'});
    check(login.status === 200 && login.body.accessToken, 'admin login'); const admin = login.body.accessToken;
    check((await request('/auth/refresh-token','POST',{},null,login.cookie)).status === 200, 'cookie refresh without in-memory token');
    check((await request('/appointments')).status === 401, 'admin appointments reject anonymous access');
    const signup = await request('/auth/register','POST',{name:'Test Patient',email:'patient@example.test',phone:'01700000002',password:'TestOnly!12345'});
    check(signup.status === 200 && signup.body.accessToken, 'patient signup'); const patient = signup.body.accessToken;
    check((await request('/appointments','GET',null,patient)).status === 403, 'patient cannot access admin appointments');
    const profile = await request('/auth/profile','PATCH',{dob:'1995-02-03',address:{street:'Test Road',city:'Dhaka'}},patient);
    check(profile.status === 200, 'patient profile address and DOB save');
    const me = (await request('/auth/me','GET',null,patient)).body.user;
    check(me.personalDetails.dob?.startsWith('1995-02-03') && me.personalDetails.address?.city === 'Dhaka', 'patient DOB and address survive database read');
    const photoForm = new FormData();
    photoForm.append('photo', new Blob([Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aD1sAAAAASUVORK5CYII=','base64')],{type:'image/png'}), 'integration.png');
    const uploadedResponse = await fetch(sandbox.base+'/auth/profile/photo',{method:'POST',headers:{authorization:`Bearer ${patient}`},body:photoForm});
    const uploaded = await uploadedResponse.json();
    check(uploadedResponse.status === 200 && uploaded.data.profilePhoto.startsWith('/uploads/profilePhoto/'), 'multipart profile photo upload');
    check((await fetch(sandbox.base.replace(/\/api$/,'')+uploaded.data.profilePhoto)).status === 200, 'uploaded profile asset can be retrieved');
    check((await request('/auth/me','GET',null,patient)).body.user.profilePhoto === uploaded.data.profilePhoto, 'profile photo path persists');
    // Remove only this API-created test file, never a production upload.
    const path = require('node:path');
    const uploadRoot = path.resolve(__dirname,'../uploads/profilePhoto');
    const testFile = path.resolve(__dirname,'..',uploaded.data.profilePhoto.slice(1));
    assert.equal(path.dirname(testFile),uploadRoot);
    await require('node:fs/promises').unlink(testFile);
    check((await request('/auth/register','POST',{name:'Short Password',email:'short@example.test',phone:'01700000009',password:'123456'})).status === 400, 'short password returns validation error instead of 500');
    const doctorId = String(sandbox.doctor._id);
    const hospital = await request('/hospital/basic-info','POST',{name:'Test Hospital',type:'Private',phone:'01700000003',email:'hospital@example.test',status:'Active'},admin);
    check(hospital.status === 201, `hospital creation (${hospital.status}: ${hospital.body.message})`);
    const hospitalId = hospital.body.hospital._id || hospital.body.hospital.id;
    check((await request(`/hospital/${hospitalId}/departments`,'POST',{name:'Cardiology',doctors:[doctorId]},admin)).status === 201, 'admin links doctor to hospital department');
    check((await request(`/hospital/${hospitalId}`)).body.departments[0].doctors[0].personalDetails.firstName === 'Demo', 'hospital returns populated doctor profile');
    const publicDoctors = await request('/doctor?status=Active&limit=1');
    const adminDoctors = await request('/doctor?status=Active&limit=1','GET',null,admin);
    check(publicDoctors.body.totalItems === adminDoctors.body.totalItems, 'active doctor counts match admin and public scopes');
    check((await request('/doctor?district=Dhaka&specialization=Cardiology')).body.totalItems === 1, 'district and specialty filters match');
    check((await request('/doctor?search=NoMatchingDoctor')).body.totalItems === 0, 'doctor name search excludes nonmatches');
    const post = await request('/blogs','POST',{title:'Integration Article',slug:'integration-article',summary:'Test summary',content:'Test article content',category:'Test',authorName:'Test Author',status:'published'},admin);
    check(post.status === 201, 'admin publishes blog article');
    check((await request('/blogs/integration-article')).status === 200, 'published blog detail can be read');
    check((await request('/blogs?category=Test&limit=1')).body.pagination.totalItems === 1, 'blog filtering and pagination');
    check((await request('/hospital/basic-info','POST',{name:'Invalid Hospital',type:'Private'},admin)).status === 400, 'hospital missing required fields returns 400');
    for (const [kind,id] of [['doctor',doctorId],['hospital',hospitalId]]) {
      const review = await request(`/${kind}/${id}/reviews`,'POST',{patientName:'Test Patient',rating:5,comment:'Helpful consultation and clear advice.'},patient);
      check(review.status === 201, `${kind} review submission`);
      check((await request(`/${kind}/${id}/reviews`)).body.data.length === 0, `${kind} pending review stays moderated`);
      check((await request(`/reviews/${review.body.data._id}`,'PATCH',{status:'approved'},admin)).status === 200, `${kind} admin review approval`);
      const published = await request(`/${kind}/${id}/reviews`);
      check(published.body.data.length === 1 && published.body.summary.averageRating === 5, `${kind} approved review and rating render data`);
      const provider = (await request(`/${kind}/${id}`)).body;
      check((kind === 'hospital' ? provider.basicInfo : provider).reviewCount === 1, `${kind} profile rating summary is persisted`);
    }
    const date = new Date(); date.setDate(date.getDate()+2); const day = date.toISOString().slice(0,10);
    const booking = {doctorId,patientName:'Test Patient',patientPhone:'01700000002',appointmentDate:`${day}T10:00:00+06:00`,timeSlot:'10:00'};
    const appointment = await request('/appointments','POST',booking,patient);
    check(appointment.status === 201, 'appointment creation');
    check((await request('/appointments','POST',booking,patient)).status === 409, 'duplicate appointment rejected');
    check((await request('/appointments','GET',null,admin)).body.data.some(x=>x._id === appointment.body.data._id), 'appointment visible to admin');
    check((await request(`/appointments/${appointment.body.data._id}`,'PATCH',{status:'confirmed'},admin)).status === 200, 'admin confirms appointment');
    const tracked = await request(`/appointments/track?appointmentNumber=${appointment.body.data.appointmentNumber}&phone=01700000002`);
    check(tracked.body.data.status === 'confirmed', 'patient tracks confirmed appointment');
    check((await request(`/appointments/${appointment.body.data._id}/cancel`,'PATCH',{},patient)).status === 200, 'patient cancels own appointment');
    const ambulance = await require('../models/Ambulance').create({basicInfo:{vehicleNumber:'TEST-001',type:'Basic',driverName:'Test Driver'},contact:{phone:'01700000005'},availability:{isAvailable:true}});
    const ride = await request('/ambulance-requests','POST',{pickupLocation:'Test Road',dropLocation:'Test Hospital',serviceType:'Basic',scheduledAt:`${day}T11:00:00+06:00`,patientName:'Test Patient',contactNumber:'01700000002'});
    check(ride.status === 201, 'ambulance booking');
    const rideId = ride.body.data._id;
    check((await request('/ambulance-requests','GET',null,admin)).body.data.some(x=>x._id===rideId), 'ambulance booking reaches admin');
    check((await request(`/ambulance-requests/${rideId}`,'PATCH',{ambulance:String(ambulance._id)},admin)).body.data.status === 'assigned', 'admin assigns ambulance');
    const competing = await require('../models/AmbulanceRequest').create({ambulance:ambulance._id,pickupLocation:'Other Road',dropLocation:'Test Hospital',serviceType:'Basic',scheduledAt:new Date(`${day}T11:00:00+06:00`),patientName:'Other Patient',contactNumber:'01700000013'});
    check((await request(`/ambulance-requests/${competing._id}`,'PATCH',{status:'assigned'},admin)).status === 409, 'busy ambulance cannot be assigned to a second preselected request');
    const rideCredentials = {requestNumber:ride.body.data.requestNumber,contactNumber:'01700000002'};
    check((await request('/ambulance-requests/track/action','POST',{...rideCredentials,action:'accept'})).body.data.customerAcceptedAt, 'patient accepts assigned ambulance');
    check((await request('/ambulance-requests/track/action','POST',{...rideCredentials,action:'cancel'})).body.data.status === 'cancelled', 'patient cancels ambulance');
    check((await require('../models/Ambulance').findById(ambulance._id)).availability.isAvailable, 'cancelled ambulance becomes available');
    check((await request(`/ambulance/${ambulance._id}`,'DELETE',null,admin)).status === 200, 'admin removes ambulance');
    const blood = await request('/blood-requests','POST',{patientName:'Test Patient',bloodGroup:'A+',hospital:'Test Hospital',requiredDate:day,contactNumber:'01700000002',urgency:'normal'});
    check(blood.status === 201, 'blood request saved');
    check((await request(`/blood-requests/${blood.body.data._id}`,'PATCH',{status:'matched'},admin)).status === 200, 'admin updates blood request');
    check((await request(`/blood-requests/track?requestNumber=${blood.body.data.requestNumber}&contactNumber=01700000002`)).body.data.status === 'matched', 'patient tracks blood request');
    const donor = await request('/blood-donor/register','POST',{name:'Test Donor',gender:'Male',dob:'1995-02-03',bloodGroup:'A+',location:'Dhaka',contactNumber:'01700000004',healthConfirm:true});
    check(donor.status === 201, 'blood donor registration'); const donorId = donor.body.data.id;
    check((await request(`/blood-donor/${donorId}/donation-info`,'PUT',{totalDonations:3,lastDonationDate:'2025-01-01',isActive:true,notes:'Test history'},admin)).status === 200, 'donation history and availability saved');
    check((await request(`/blood-donor/${donorId}/address`,'PUT',{address:'Test Road',city:'Dhaka',state:'Dhaka'},admin)).body.address.city === 'Dhaka', 'donor address save response');
    check((await request(`/blood-donor/${donorId}/basic-info`,'PUT',{firstName:'Updated'},admin)).status === 200, 'partial donor profile update');
    const saved = (await request(`/blood-donor/${donorId}`)).body.donor;
    check(saved.basicInfo.dob.startsWith('1995-02-03') && saved.address.city === 'Dhaka' && saved.donationInfo.totalDonations === 3, 'DOB address and donation history persisted after update');
    const later = await require('../models/BloodDonor').create({basicInfo:{firstName:'Later',lastName:'Donor',gender:'Male',dob:'1990-01-01',bloodGroup:'B+'},contact:{phone:'01700000008'},donationInfo:{isActive:true,totalDonations:10,availableFrom:new Date(Date.now()+30*86400000)},address:{city:'Khulna'}});
    check((await request('/blood-donor?isActive=true&availability=now')).body.donors.every(x=>x._id!==String(later._id)), 'availability filter excludes future donors');
    check((await request('/blood-donor?isActive=true&sort=donations&limit=1')).body.donors[0]._id===String(later._id), 'donation sort works before pagination');
    check((await request('/blood-donor?isActive=true&limit=1&page=2')).body.pagination.totalItems === 2, 'donor pagination preserves total count');
    const inquiry = await request('/contact-inquiries','POST',{name:'Test Patient',email:'patient@example.test',subject:'Test inquiry',message:'Isolated integration test message'});
    check(inquiry.status === 201, 'contact inquiry saved');
    check((await request('/contact-inquiries','GET',null,admin)).body.data.some(x=>x.referenceNumber === inquiry.body.data.referenceNumber), 'contact inquiry reaches admin');
    check((await request(`/blood-donor/${donorId}`,'DELETE',null,admin)).status === 200, 'admin donor removal');
    check((await request(`/blood-donor/${donorId}`)).status === 404, 'removed donor no longer returned');
    console.log(`INTEGRATION RESULT: ${assertions} assertions passed`);
  } finally { await sandbox.close(); }
}
run().catch(error => { console.error(error); process.exitCode=1; });
