name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Load PNPM binary
            export PNPM_HOME="/root/.local/share/pnpm"
            export PATH="$PNPM_HOME:$PATH"

            echo "Using PNPM: $(which pnpm)"

            # Go to server directory
            cd /root/doctorekhane-server-site

            # Pull latest source
            git pull origin main

            # Install dependencies
            pnpm install

            # Restart PM2 process
            pm2 restart doctorekhane-server

            echo "🚀 Server deployment completed!"
